### ISSUE TITLE
字体大小 整体大小

### ISSUE THREAD

**Issue by q872839000** [PixelChen24/Magirror#6]
方便教一下 怎么调整整个大小吗

**Comment by PixelChen24** [comment]
> 方便教一下 怎么调整整个大小吗

目前暂时没有一键修改字体大小的功能。不过您可以通过修改源代码实现。

具体操作为：
您可以在源代码[主文件](`main.py`)中找到许多show()函数，那些函数都是在绘制文字或图片。在这些函数中，`font.render_to`是用来以字体`font`向屏幕上渲染的语句，您可以修改font的属性，进而修改显示出的字体大小。

例如在`main.py`的112行
```python
    dateFont = pygame.freetype.Font('./FontLib/setup/苹方黑体-准-简.ttf', 36)
    dateFont.render_to(screen, (100, 260), Date, white)
    dateFont.render_to(screen, (140, 300), Lunar, white)
```

表示选定字体dateFont为"苹方黑体-准-简.ttf"，字号为36，下面两行代码的意思就是用这种字体在屏幕的(100,260)坐标和(140,300)坐标分别以字体颜色`white`渲染文字Date和Lunar

---
本人最近事务比较繁忙，等过两三个月闲下来会考虑加入适配分辨率、大小、旋转等问题，感谢您的支持！

**Comment by q872839000** [comment]
好的，谢谢，我看很多地方都是写死的布局，建议可以做成自适应的，这样相信大众更喜欢，东西做得很棒，加油~
